<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Multicart
 * @version     1.0
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2015 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @var $this Mage_Checkout_Block_Cart
 */
if(Mage::getStoreConfig("multicart/catalog/enabled")){
$helper = Mage::helper('multicart');
/**
 * Adding Session Message
 */
echo $this->getMessagesBlock()->getGroupedHtml();
/**
 * Defining Array
 */
$sellerIds = array();
/**
 * Get Items From Custom Session
 */
$splitCartItems = Mage::getSingleton('core/session')->getAppthaMpSplitCart();
/**
 * Incrementing Foreach loop
 */
foreach($this->getItems() as $_item){
/**
 * Getting Product Id
 */
$productId = $_item->getProductId();
/**
 * Getting Seller Id
 */
$sellerId = Mage::getModel('catalog/product')->load($productId)->getSellerId();
/**
 * Checking whether seller id exists or not
 */
if(array_key_exists($sellerId,$sellerIds)){
$currentProductArr = $sellerIds[$sellerId];
$currentProductArr[] = $productId; 
$sellerIds[$sellerId] = $currentProductArr;
}else{
$sellerIds[$sellerId] = array($productId); 
}
}
?>
<?php 
/**
 * Getting Total Items In cart
 */
$totalItemsInCart = Mage::helper('checkout/cart')->getItemsCount();
        if(empty($totalItemsInCart)){?>
        
      <div class="cartempty">
      <?php 
      /**
       * Showing Page title
       */
      
      ?>
<div class="page-title">
    <h1><?php echo $this->__('Shopping Cart') ?>
    <span><?php echo $this->__(' is Empty') ?></span></h1>
</div>
<?php 
/**
 * Showing Empty cart 
 */

?>
<div class="cart-empty">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('checkout_cart_empty_widget'); ?>
    <p><?php echo $this->__('You have no items in your shopping cart.') ?></p>
    <p><?php echo $this->__('Click <a href="%s">here</a> to continue shopping.', $this->getContinueShoppingUrl()) ?></p>
    <?php echo $this->getChildHtml('shopping.cart.table.after'); ?>
</div>
</div>
     <?php    }
?>
<?php $_priceDisplay = ($this->helper('tax')->displayCartBothPrices()) ? 'display-both-prices' : 'display-single-price'; ?>
<?php 
/**
 * Checking Whether cart empty or not
 */
?>
<?php  if(!empty($totalItemsInCart)){?>
<div class="cart <?php echo $_priceDisplay; ?>">
 <div class="page-title title-buttons">
  <h1><span><?php echo $this->__('Shopping') ?></span> 
        <?php echo $this->__('Cart') ?></h1>
        </div>
<?php
/**
 * Incrementing foreach loop
 */
$sellerCheckoutFlag=0;
foreach($sellerIds as $sellerId => $sellerProducts){
/**
 * Get Store Name
 */
$storeName = Mage::getModel('marketplace/sellerprofile')->getCollection()
->addFieldToFilter('seller_id', $sellerId)->getFirstItem()->getStoreTitle();
/**
 * Getting Seller Name
 */
$customerData = Mage::getModel('customer/customer')->load($sellerId)->getData();
/**
 * Get Seller Name
 */
$sellerName= ($customerData['firstname']);
/**
 * Declare seller id, grand total & subtotal
 */
$grandTotal = 0;
$subTotal = 0;
?>
<?php $_priceDisplay = ($this->helper('tax')->displayCartBothPrices()) ? 'display-both-prices' : 'display-single-price'; ?>
<div class="page-title title-buttons">
<?php if($storeName!="" || $sellerName !=""){?>
        <h3>
<span><?php echo $this->__('Seller') ?></span> 
        <?php
        /**
         * Showing Store Name
         */
            if ($storeName != "") {
                echo " : ".$storeName;
            }
/**
 * Showing seller Name
 */
          elseif ($sellerName != "") {
                echo ucfirst ( strtolower ( $sellerName ) );
           }
?></h3>
        <?php }?>
    </div>
  
    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>"
method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <table id="shopping-cart-table" class="cart-table data-table">
     <col width="1" />
     <col width="1" />
     <col width="1" />
     <col width="1" />
     <col width="1" />
     <col width="1" />
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <col width="1" />
            <col width="1" />
            <?php endif; ?>

        <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
            <thead>
<tr>
<th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Product') ?></span></th>
<th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
<th class="a-center cart-price-head"
colspan="<?php echo $mergedCells; ?>">
<!--                            <div class="cart-price-placeholder">-->
<span class="nobr"><?php echo $this->__('Price') ?></span> <!--                            </div>-->
</th>
<th rowspan="<?php echo $mergedCells; ?>" class="a-center">
                        <?php echo $this->__('Qty') ?>
                        <?php /*if ($this->helper('wishlist')->isAllowInCart()) : ?>
                            <span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span>
                        <?php endif*/ ?>

                    </th>
<th class="a-center cart-total-head"
colspan="<?php echo $mergedCells; ?>">
<!--                            <div class="cart-total-placeholder">-->
                            <?php echo $this->__('Subtotal') ?>
<!--                            </div>-->
</th>
<th class="a-center" rowspan="<?php echo $mergedCells; ?>">
                    <?php echo $this->__('Action') ?>
                    </th>
</tr>
 <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <tr>
<th class="a-center cart-price-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
<th class="a-center cart-price-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
<th class="a-center cart-total-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
<th class="a-center cart-total-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
</tr>
                <?php endif; ?>
            </thead>
<tfoot>
<tr>
<td colspan="50" class="a-right cart-footer-actions">
<!-- Make this button the first responder rather than empty cart -->
<button type="submit" style="visibility: hidden;"
name="update_cart_action" value="update_qty"
title="<?php echo $this->__('Update Shopping Cart'); ?>"
class="button2 btn-update">
<span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span>
</button>

<button type="submit" name="update_cart_action"
value="<?php  echo implode(',', $sellerProducts)?>"
title="<?php echo $this->__('Empty Cart'); ?>"
class="button2 btn-empty" id="empty_cart_button">
<span><span><?php echo $this->__('Empty Cart'); ?></span></span>
</button>

<button type="submit" name="update_cart_action" value="update_qty"
title="<?php echo $this->__('Update Shopping Cart'); ?>"
class="button2 btn-update">
<span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span>
</button> <span class="or">-or-</span>

                        <?php if($this->getContinueShoppingUrl()): ?>
                            <button type="button"
title="<?php echo $this->__('Continue Shopping') ?>"
class="button2 btn-continue"
onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')">
<span><span><?php echo $this->__('Continue Shopping') ?></span></span>
</button>
                        <?php endif; ?>
                        <!--[if lt IE 8]>
                        <input type="hidden" id="update_cart_action_container" />
                        <script type="text/javascript">
                        //<![CDATA[
                            Event.observe(window, 'load', function()
                            {
                                // Internet Explorer (lt 8) does not support value attribute in button elements
                                $emptyCartButton = $('empty_cart_button');
                                $cartActionContainer = $('update_cart_action_container');
                                if ($emptyCartButton && $cartActionContainer) {
                                    Event.observe($emptyCartButton, 'click', function()
                                    {
                                        $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                                        $cartActionContainer.setAttribute('name', 'update_cart_action');
                                        $cartActionContainer.setValue('empty_cart');
                                    });
                                }

                            });
                        //]]>
                        </script>
                        <![endif]-->
</td>
</tr>
</tfoot>
<tbody>
            <?php 
            /**
             * Incrementing foreach loop
             */
            foreach($this->getItems() as $_item){ 
               /**
                 * Checking whether in array or not
                 * 
                 * 
                */          
     if(in_array($_item->getProductId(),$sellerProducts)){
  /**
   * Getting qty
   */
            $qty = $_item->getQty() ;
            /**
             * Getting Price
             */
            $price = $_item->getPrice();
            /**
             * Total Price
             */
            $totalPrice =  $qty * $price;
            /**
             * Grand Total
             */
            $grandTotal = $grandTotal + $totalPrice;
            /**
             * Sub total
             */
            $subTotal = $subTotal + $totalPrice;   
            /**
             * load Product and get stock
             */
            $model = Mage::getModel('catalog/product');
            $_product = $model->load($_item->getProductId());
            $assignProduct= $_product->getIsAssignProduct();
           
           $visibilty=   $isVisibleProduct = $_product->isVisibleInSiteVisibility();
              $customerId= $_product->getCustomerId();
        
          
            /**
             * Get Inventory
             */
            if( $_product->getTypeId() != 'configurable' ){
            /**
             * Checking Whether Qty is > than Stock
               */

            $stocklevel = (int)Mage::getModel('cataloginventory/stock_item')
            ->loadByProduct($_product)->getQty();
            }
            else{

             $product=Mage::getModel("catalog/product");
            $prod=$product->load($_item->getProductId());
            $conf = Mage::getModel('catalog/product_type_configurable')->setProduct($prod);
            $col = $conf->getUsedProductCollection()->addAttributeToSelect('*')->addFilterByRequiredOptions();
            
            $total_qty=0;
            foreach($col as $sprod){
                $sprod=$product->load($sprod->getId());
                $stockQty = intval(Mage::getModel('cataloginventory/stock_item')->loadByProduct($sprod)->getQty());
                $stocklevel+=$stockQty;
            }
            }
            
          
       if($qty>$stocklevel){
/**
 * Set flag as 1
 */
              $flag=1;
              $sellerCheckoutFlag=1;
              }
            else{
/**
 * Set Flag as 0
 */
             $flag=0;
             }
            ?>
            <?php
/**
 * Get Item Details
 */
          
            if($visibilty==4 && $assignProduct ==0  ||$visibilty!=4 && $assignProduct ==1){
        echo $this->getItemHtml($_item);
        }
            ?>
            <?php }
             } 
             ?>
            </tbody>
</table>
<script type="text/javascript">decorateTable('shopping-cart-table')</script>

</form>
    <?php 
    /**
     * Getting Currency Symbol
     */
      $currencySymbol= Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();?>
        <div class="cart-totals-wrapper">
<div class="cart-totals">
<table id="shopping-cart-totals-table">
<colgroup>
<col>
<col width="1">
</colgroup>
<tfoot>
<?php 
/**
 * 
 * Showing Grand Total
 */
?>
<tr>
<td style="" class="a-right" colspan="1"><strong><?php echo $this->__('Grand Total'); ?></strong>
</td>
<td style="" class="a-right"><strong><span class="price"><?php echo   $currencySymbol.number_format($grandTotal);; ?></span></strong>
</td>
</tr>
</tfoot>
<tbody>
<?php 
/**
 * 
 * Showing Sub Total
 */
?>
<tr>
<td style="" class="a-right" colspan="1"> <?php echo $this->__('Subtotal'); ?> </td>
<td style="" class="a-right"><span class="price"><?php echo $currencySymbol.number_format($subTotal); ?></span>
</td>
</tr>
</tbody>
</table>
<?php 
/**
 * Checking Onestepcheckout enabled or not
 */
$oneStepCheckoutEnabled=Mage::getStoreConfig("onestepcheckout/general/Activate_apptha_onestepcheckout");
/**
 * Check whther onestepcheckout should display in cart or not
*/
$displayInCart=Mage::getStoreConfig("onestepcheckout/general/Activate_apptha_onestepcheckout_cart");
/**
 * Defining url for checkout button
*/
if($oneStepCheckoutEnabled && $displayInCart==0 ){
    /**
     * Onestepcheckout url
     */
    $url=Mage::getUrl('onestepcheckout');
}
else{
    /**
     * Onepage Url
     */
    $url= Mage::getUrl('checkout/onepage');
}
?>
<form action="<?php echo $url ?>" method="POST">
<ul class="checkout-types bottom">
<li class="method-checkout-cart-methods-onepage-bottom">
<?php 
/**
 * Checkout Button
 */
if($flag!=1 &&  $sellerCheckoutFlag!=1){?>

<input type="hidden" name="s" value="<?php echo $sellerId?>"/>
<button  type="submit" title="Proceed to Checkout"
            class="button btn-proceed-checkout btn-checkout">
<span><span><?php echo $this->__('Proceed to Checkout');  ?></span></span>
</button>
<?php
}?>
</li>
</ul>
</form>
</div>
</div>
<?php  
/**
 * Setting Seller Flag Again to Zero
 */
$sellerCheckoutFlag=0;
}
?>
<?php }?>
</div>
<?php } ?>
<style>
.page-title{
clear:both;
}
</style>
